### ISSUE TITLE
Sorting Algorithm for Elements of Masters that are Collections

### ISSUE THREAD

**Issue by juanmriosv** [Century21Stores/GLOBAL#27] opened 2016-08-25 13:26 UTC
Note: related to https://jira.tools.weblinc.com/browse/CENTURYROR-556

But for masters that are collections, we would want to change the ordering ourselves – Bedding Collections (Duvet, Sheets, Pillows) , Dinnerware (Dinner Plate, Salad Plate, Bowl, Dessert Plate, Mug) Activewear (Top, Bottom, Shoes, Accessories) Swimwear (Top, Bottom) Towels (Bath Towel, Hand Towel, Washcloth)
https://www.c21stores.com/products/altalena-sheet-set

**Comment by c21hornak** [comment] 2017-01-05 01:47
@juanmriosv just curious how you plan on making this work? With a Google Spreadsheet / database?

**Comment by juanmriosv** [comment] 2017-01-05 02:14
@c21hornak, I change a bit the wording of the ticket's title. I thinking to apply the same I did for the sizes on PDP. In case of master, I will rearrange the elements based on their size.

**Comment by juanmriosv** [comment] 2017-02-14 21:21
@c21hornak I believe this is the same as
[https://github.com/Century21Stores/GLOBAL/issues/25](https://github.com/Century21Stores/GLOBAL/issues/25)

**Comment by c21hornak** [comment] 2017-02-16 02:48
@juanmriosv in the pipeline, is this pushed to production?

**Comment by juanmriosv** [comment] 2017-02-16 02:52
@c21hornak in pipeline.
I believe this is the same as [25](https://github.com/Century21Stores/GLOBAL/issues/25)

**Comment by c21hornak** [comment] 2017-02-16 02:55
So there is no code associated with this? All work for both https://github.com/Century21Stores/GLOBAL/issues/27 and https://github.com/Century21Stores/GLOBAL/issues/25 was done on https://github.com/Century21Stores/GLOBAL/issues/25?

**Comment by c21hornak** [comment] 2017-12-27 21:19
@juanmriosv @ashahinC21 can we close this if it's a duplicate of https://github.com/Century21Stores/GLOBAL/issues/25 ?

**Comment by ashahinC21** [comment] 2017-12-28 14:19
Closing this issue (duplicate of #25).

**Closed as completed by ashahinC21** 2017-12-28 14:19 UTC
Labels: bug weblinc
